name: Backend Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  merge:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
  build:
    runs-on: self-hosted
    needs: merge
    steps:    
    - name: Build the Docker image
      run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/cicd:latest
      shell: powershell

    #- name: Log into Docker Hub
    #  uses: docker/login-action@v3
     # with:
     #   username: ${{ secrets.DOCKERHUB_USERNAME }}
     #   password: ${{ secrets.DOCKERHUB_TOKEN }}

    #- name: Push the image to Docker Hub
    #  run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/cicd:latest
    
  deploy:
    runs-on: self-hosted
    needs: build
    steps: 
    - name: Run the image 
      run: |
        docker stop cicd
        docker rm cicd
        docker run -d -p 8888:80 --name cicd ${{ secrets.DOCKERHUB_USERNAME }}/cicd:latest
      shell: powershell
    
      #uses: appleboy/ssh-action@v1.0.3
      #with:
        #host: ${{ secrets.SSH_HOST }}
        #username: ${{ secrets.SSH_USERNAME }}
        #password: ${{ secrets.SSH_PASSWORD }}
        #debug: true
        #key: ${{ secrets.SSH_PRIVATE_KEY }}
        #script: 
          #echo "Connected successfully"
          #docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cicd:latest
          #docker stop cicd || true
          #docker rm cicd || true
          #docker run -d -p 8888:80 --name cicd ${{ secrets.DOCKERHUB_USERNAME }}/cicd:latest
